export const PRACTICE_LEN = 4;
export const KEYS_ACCEPT_DECLINE = ['j','k']; // TODO use everywhere!
export const KEY_RIG = 's'; // TODO use everywhere!

export const URL_REDIRECT =  "https://survey2.edu.uni-graz.at/919136/lang-de";

export const IMG ={};

IMG.INSTRUCTION_STAIR_PHON_J_PRACTICE = new Image();
IMG.INSTRUCTION_STAIR_PHON_J= new Image();

IMG.INSTRUCTION_STAIR_PHON_K_PRACTICE = new Image();
IMG.INSTRUCTION_STAIR_PHON_K= new Image();

IMG.INSTRUCTION_STAIR_VIS_J_PRACTICE = new Image();
IMG.INSTRUCTION_STAIR_VIS_J= new Image();

IMG.INSTRUCTION_STAIR_VIS_K_PRACTICE = new Image();
IMG.INSTRUCTION_STAIR_VIS_K= new Image();

IMG.INSTRUCTION_SINGLE_J_PRACTICE = new Image();
IMG.INSTRUCTION_SINGLE_J= new Image();

IMG.INSTRUCTION_SINGLE_K_PRACTICE = new Image();
IMG.INSTRUCTION_SINGLE_K= new Image();

IMG.INSTRUCTION_DUAL_PHON_J_PRACTICE = new Image();
IMG.INSTRUCTION_DUAL_PHON_J= new Image();

IMG.INSTRUCTION_DUAL_PHON_K_PRACTICE = new Image();
IMG.INSTRUCTION_DUAL_PHON_K= new Image();

IMG.INSTRUCTION_DUAL_VIS_J_PRACTICE = new Image();
IMG.INSTRUCTION_DUAL_VIS_J= new Image();

IMG.INSTRUCTION_DUAL_VIS_K_PRACTICE = new Image();
IMG.INSTRUCTION_DUAL_VIS_K= new Image();

IMG.INSTRUCTION_RIG_J_PRACTICE = new Image();
IMG.INSTRUCTION_RIG_J= new Image();

IMG.INSTRUCTION_RIG_K_PRACTICE = new Image();
IMG.INSTRUCTION_RIG_K= new Image();

IMG.INSTRUCTION_RIG_2 = new Image();




IMG.FEEDBACK_VIS_CORRECT = new Image();
IMG.FEEDBACK_VIS_INCORRECT = new Image();

IMG.FEEDBACK_PHON_CORRECT = new Image();
IMG.FEEDBACK_PHON_INCORRECT = new Image();

IMG.FEEDBACK_ORD_CORRECT = new Image();
IMG.FEEDBACK_ORD_INCORRECT = new Image();
