export const PRACTICE_LEN = 2;
export const KEYS_ACCEPT_DECLINE = ['j','k']; // TODO use everywhere!
export const KEY_RIG = 's'; // TODO use everywhere!

export const INSTRUCTION_STAIR_PHON_J= 'In den folgenden Folien wird Ihnen eine Buchstabenfolge präsentiert, die Sie sich einprägen sollen. \nDanach wird Ihnen ein Fixationspunkt, auf den Sie sich konzentrieren sollen, präsentiert. \nIm Anschluss wird Ihnen erneut eine Buchstabenfolge präsentiert. \nSie sollen nun entscheiden, ob die beiden Buchstabenfolgen übereinstimmen. \nSollte dies der Fall sein, drücken Sie J, sollten sich die zwei Buchstabenfolgen voneinander unterscheiden drücken Sie K. \nBitte verwenden Sie hierfür den Zeigefinger und den Mittelfinger der rechten Hand. \nNach Ihrer Antwort bekommen Sie erneut einen Fixationspunkt zu sehen. \nDieser Ablauf wiederholt sich mehrmals.  \nAchtung! Hierbei spielt Groß- und Kleinschreibung keine Rolle.  \n\nLegen Sie nun den rechten Zeigefinger auf J (übereinstimmende Buchstabenfolgen) und den rechten Mittelfinger auf K (keine übereinstimmenden Buchstabenfolgen).  \n\nDer Übungsdurchlauf ist nun beendet. \nDrücken sie J, um mit der tatsächlichen Testung zu beginnen . ';
export const INSTRUCTION_STAIR_PHON_J_PRACTICE = 'In den folgenden Folien wird Ihnen eine Buchstabenfolge präsentiert, die Sie sich einprägen sollen. \nDanach wird Ihnen ein Fixationspunkt, auf den Sie sich konzentrieren sollen, präsentiert. \nIm Anschluss wird Ihnen erneut eine Buchstabenfolge präsentiert. \nSie sollen nun entscheiden, ob die beiden Buchstabenfolgen übereinstimmen. \nSollte dies der Fall sein, drücken Sie J, sollten sich die zwei Buchstabenfolgen voneinander unterscheiden drücken Sie K. \nBitte verwenden Sie hierfür den Zeigefinger und den Mittelfinger der rechten Hand. \nNach Ihrer Antwort bekommen Sie erneut einen Fixationspunkt zu sehen. \nDieser Ablauf wiederholt sich mehrmals.  \nAchtung! Hierbei spielt Groß- und Kleinschreibung keine Rolle.  \n\nLegen Sie nun den rechten Zeigefinger auf J (übereinstimmende Buchstabenfolgen) und den rechten Mittelfinger auf K (keine übereinstimmenden Buchstabenfolgen).  \n\nWenn Sie die Instruktion verstanden haben drücken sie J, um mit Übungsdurchgängen zur Aufgabe zu starten.';

export const INSTRUCTION_STAIR_PHON_K= 'In den folgenden Folien wird Ihnen eine Buchstabenfolge präsentiert, die Sie sich einprägen sollen. \nDanach wird Ihnen ein Fixationspunkt, auf den Sie sich konzentrieren sollen, präsentiert. \nIm Anschluss wird Ihnen erneut eine Buchstabenfolge präsentiert. \nSie sollen nun entscheiden, ob die beiden Buchstabenfolgen übereinstimmen. \nSollte dies der Fall sein, drücken Sie K, sollten sich die zwei Buchstabenfolgen voneinander unterscheiden drücken Sie J. \nBitte verwenden Sie hierfür den Zeigefinger und den Mittelfinger der rechten Hand. \nNach Ihrer Antwort bekommen Sie erneut einen Fixationspunkt zu sehen. \nDieser Ablauf wiederholt sich mehrmals.  \nAchtung! Hierbei spielt Groß- und Kleinschreibung keine Rolle.  \n\nLegen Sie nun den rechten Zeigefinger auf J (keine übereinstimmenden Buchstabenfolgen) und den rechten Mittelfinger auf K (übereinstimmende Buchstabenfolgen).  \n\nDer Übungsdurchlauf ist nun beendet. \nDrücken sie K, um mit der tatsächlichen Testung zu beginnen.';


export const INSTRUCTION_STAIR_PHON_K_PRACTICE = ' In den folgenden Folien wird Ihnen eine Buchstabenfolge präsentiert, die Sie sich einprägen sollen. \nDanach wird Ihnen ein Fixationspunkt, auf den Sie sich konzentrieren sollen, präsentiert. \nIm Anschluss wird Ihnen erneut eine Buchstabenfolge präsentiert. \nSie sollen nun entscheiden, ob die beiden Buchstabenfolgen übereinstimmen. \nSollte dies der Fall sein, drücken Sie K, sollten sich die zwei Buchstabenfolgen voneinander unterscheiden drücken Sie J. \nBitte verwenden Sie hierfür den Zeigefinger und den Mittelfinger der rechten Hand. \nNach Ihrer Antwort bekommen Sie erneut einen Fixationspunkt zu sehen. \nDieser Ablauf wiederholt sich mehrmals.  \nAchtung! Hierbei spielt Groß- und Kleinschreibung keine Rolle.  \n\nLegen Sie nun den rechten Zeigefinger auf J (keine übereinstimmenden Buchstabenfolgen) und den rechten Mittelfinger auf K (übereinstimmende Buchstabenfolgen).  \n\nWenn Sie die Instruktion verstanden haben drücken sie K, um mit Übungsdurchgängen zur Aufgabe zu starten.';

export const INSTRUCTION_STAIR_VIS_J= 'In den folgenden Folien wird Ihnen ein Muster präsentiert, das Sie sich einprägen sollen. \nDanach wird Ihnen ein Fixationspunkt, auf den Sie sich konzentrieren sollen, präsentiert. \nIm Anschluss wird Ihnen erneut ein Muster präsentiert. \nSie sollen nun entscheiden, ob die beiden Muster übereinstimmen. \nSollte dies der Fall sein, drücken Sie J, sollten sich die zwei Muster voneinander unterscheiden drücken Sie K. \nBitte verwenden Sie hierfür den Zeigefinger und den Mittelfinger der rechten Hand. \nNach Ihrer Antwort bekommen Sie erneut einen Fixationspunkt zu sehen. \nDieser Vorgang wiederholt sich mehrmals.  \n\nLegen Sie nun den rechten Zeigefinger auf J (übereinstimmende Muster) und den rechten Mittelfinger auf K (keine übereinstimmenden Muster).  \n\nDer Übungsdurchlauf ist nun beendet. \nDrücken sie J, um mit der tatsächlichen Testung zu beginnen.';

export const INSTRUCTION_STAIR_VIS_J_PRACTICE = 'In den folgenden Folien wird Ihnen ein Muster präsentiert, das Sie sich einprägen sollen. \nDanach wird Ihnen ein Fixationspunkt, auf den Sie sich konzentrieren sollen, präsentiert. \nIm Anschluss wird Ihnen erneut ein Muster präsentiert. \nSie sollen nun entscheiden, ob die beiden Muster übereinstimmen. \nSollte dies der Fall sein, drücken Sie J, sollten sich die zwei Muster voneinander unterscheiden drücken Sie K. \nBitte verwenden Sie hierfür den Zeigefinger und den Mittelfinger der rechten Hand. \nNach Ihrer Antwort bekommen Sie erneut einen Fixationspunkt zu sehen. \nDieser Vorgang wiederholt sich mehrmals.  \n\nLegen Sie nun den rechten Zeigefinger auf J (übereinstimmende Muster) und den rechten Mittelfinger auf K (keine übereinstimmenden Muster).  \nWenn Sie die Instruktion verstanden haben drücken sie J, um mit Übungsdurchgängen zur Aufgabe zu starten.';

export const INSTRUCTION_STAIR_VIS_K= 'In den folgenden Folien wird Ihnen ein Muster präsentiert, das Sie sich einprägen sollen. \nDanach wird Ihnen ein Fixationspunkt, auf den Sie sich konzentrieren sollen, präsentiert. \nIm Anschluss wird Ihnen erneut ein Muster präsentiert. \nSie sollen nun entscheiden, ob die beiden Muster übereinstimmen. \nSollte dies der Fall sein, drücken Sie K, sollten sich die zwei Muster voneinander unterscheiden drücken Sie J. \nBitte verwenden Sie hierfür den Zeigefinger und den Mittelfinger der rechten Hand. \nNach Ihrer Antwort bekommen Sie erneut einen Fixationspunkt zu sehen. \nDieser Vorgang wiederholt sich mehrmals.  \n\nLegen Sie nun den rechten Zeigefinger auf J (keine übereinstimmenden Muster) und den rechten Mittelfinger auf K (übereinstimmende Muster).  \n\nDer Übungsdurchlauf ist nun beendet. \nDrücken sie K, um mit der tatsächlichen Testung zu beginnen.';

export const INSTRUCTION_STAIR_VIS_K_PRACTICE = ' In den folgenden Folien wird Ihnen ein Muster präsentiert, das Sie sich einprägen sollen. \nDanach wird Ihnen ein Fixationspunkt, auf den Sie sich konzentrieren sollen, präsentiert. \nIm Anschluss wird Ihnen erneut ein Muster präsentiert. \nSie sollen nun entscheiden, ob die beiden Muster übereinstimmen. \nSollte dies der Fall sein, drücken Sie K, sollten sich die zwei Muster voneinander unterscheiden drücken Sie J. \nBitte verwenden Sie hierfür den Zeigefinger und den Mittelfinger der rechten Hand. \nNach Ihrer Antwort bekommen Sie erneut einen Fixationspunkt zu sehen. \nDieser Vorgang wiederholt sich mehrmals.  \n\nLegen Sie nun den rechten Zeigefinger auf J (keine übereinstimmenden Muster) und den rechten Mittelfinger auf K (übereinstimmende Muster).  \n\nWenn Sie die Instruktion verstanden haben drücken sie K, um mit Übungsdurchgängen zur Aufgabe zu starten.';

export const INSTRUCTION_SINGLE_J= 'In den folgenden Folien wird Ihnen zunächst ein Fixationspunkt, auf den Sie sich konzentrieren sollen, präsentiert. \nDanach ist kurz eine Zahlenfolge zu sehen. \nSobald sie die Zahlenfolge sehen sollen Sie entscheiden, ob die gesehen Zahlenfolge geordnet (also aufsteigend oder absteigend) oder vollkommen ungeordnet war. \nWenn die gesehene Zahlenfolge geordnet (aufsteigend oder absteigend) war drücken Sie J. \nWenn die Zahlenfolge ungeordnet war, drücken Sie K. \nBitte verwenden Sie hierfür den Zeigefinger und den Mittelfinger der rechten Hand. \nNach der Antwort sehen Sie erneut einen Fixationspunkt. \nDieser Ablauf wiederholt sich mehrmals.  \n\nLegen Sie nun den rechten Zeigefinger auf J (geordnete Zahlenfolge) und den rechten Mittelfinger auf K (ungeordnete Zahlenfolge).  \n\nDer Übungsdurchlauf ist nun beendet. \nDrücken sie J, um mit der tatsächlichen Testung zu beginnen.';

export const INSTRUCTION_SINGLE_J_PRACTICE = 'In den folgenden Folien wird Ihnen zunächst ein Fixationspunkt, auf den Sie sich konzentrieren sollen, präsentiert. \nDanach ist kurz eine Zahlenfolge zu sehen. \nSobald sie die Zahlenfolge sehen sollen Sie entscheiden, ob die gesehen Zahlenfolge geordnet (also aufsteigend oder absteigend) oder vollkommen ungeordnet war. \nWenn die gesehene Zahlenfolge geordnet (aufsteigend oder absteigend) war drücken Sie J. \nWenn die Zahlenfolge ungeordnet war, drücken Sie K. \nBitte verwenden Sie hierfür den Zeigefinger und den Mittelfinger der rechten Hand. \nNach der Antwort sehen Sie erneut einen Fixationspunkt. \nDieser Ablauf wiederholt sich mehrmals.  \n\nLegen Sie nun den rechten Zeigefinger auf J (geordnete Zahlenfolge) und den rechten Mittelfinger auf K (ungeordnete Zahlenfolge).  \n\nWenn Sie die Instruktion verstanden haben drücken sie J, um mit Übungsdurchgängen zur Aufgabe zu starten.';

export const INSTRUCTION_SINGLE_K= 'In den folgenden Folien wird Ihnen zunächst ein Fixationspunkt, auf den Sie sich konzentrieren sollen, präsentiert. \nDanach ist kurz eine Zahlenfolge zu sehen. \nSobald sie die Zahlenfolge sehen sollen Sie entscheiden, ob die gesehen Zahlenfolge geordnet (also aufsteigend oder absteigend) oder vollkommen ungeordnet war. \nWenn die gesehene Zahlenfolge geordnet (aufsteigend oder absteigend) war drücken Sie K. \nWenn die Zahlenfolge ungeordnet war, drücken Sie J. \nBitte verwenden Sie hierfür den Zeigefinger und den Mittelfinger der rechten Hand. \nNach der Antwort sehen Sie erneut einen Fixationspunkt. \nDieser Ablauf wiederholt sich mehrmals.  \n\nLegen Sie nun den rechten Zeigefinger auf J (ungeordnete Zahlenfolge) und den rechten Mittelfinger auf K (geordnete Zahlenfolge).  \n\nDer Übungsdurchlauf ist nun beendet. Drücken sie K, um mit der tatsächlichen Testung zu beginnen.';

export const INSTRUCTION_SINGLE_K_PRACTICE = ' In den folgenden Folien wird Ihnen zunächst ein Fixationspunkt, auf den Sie sich konzentrieren sollen, präsentiert. \nDanach ist kurz eine Zahlenfolge zu sehen. \nSobald sie die Zahlenfolge sehen sollen Sie entscheiden, ob die gesehen Zahlenfolge geordnet (also aufsteigend oder absteigend) oder vollkommen ungeordnet war. \nWenn die gesehene Zahlenfolge geordnet (aufsteigend oder absteigend) war drücken Sie K. \nWenn die Zahlenfolge ungeordnet war, drücken Sie J. \nBitte verwenden Sie hierfür den Zeigefinger und den Mittelfinger der rechten Hand. \nNach der Antwort sehen Sie erneut einen Fixationspunkt. \nDieser Ablauf wiederholt sich mehrmals.  \n\nLegen Sie nun den rechten Zeigefinger auf J (ungeordnete Zahlenfolge) und den rechten Mittelfinger auf K (geordnete Zahlenfolge).  \n\nWenn Sie die Instruktion verstanden haben drücken sie K, um mit Übungsdurchgängen zur Aufgabe zu starten.';

export const INSTRUCTION_DUAL_PHON_J= 'In den folgenden Folien wird Ihnen eine Buchstabenfolge präsentiert, die Sie sich einprägen sollen. \nDanach wird Ihnen ein Fixationspunkt, auf den Sie sich konzentrieren sollen, präsentiert. \nDanach ist kurz eine Zahlenfolge zu sehen. \nSobald sie die Zahlenfolge sehen sollen Sie so schnell wie möglich entscheiden, ob die gesehen Zahlenfolge geordnet (also aufsteigend oder absteigend) oder vollkommen ungeordnet war. \nWenn die gesehene Zahlenfolge geordnet (aufsteigend oder absteigend) war drücken Sie J. \nWenn die Zahlenfolge ungeordnet war, drücken Sie K. \nNach der Antwort sehen Sie erneut einen Fixationspunkt. \nAnschließend sehen Sie erneut eine Buchstabenfolge. \nSie sollen nun entscheiden, ob diese Buchstabenfolge, mit der zu Beginn Gezeigten übereinstimmt. \nSollte dies der Fall sein, drücken Sie J, sollten sich die zwei Buchstabenfolgen voneinander unterscheiden drücken Sie K. \nBitte verwenden Sie hierfür jeweils den Zeigefinger und den Mittelfinger der rechten Hand. \nDieser Ablauf wiederholt sich mehrmals.  \nAchtung! Hierbei spielt Groß- und Kleinschreibung keine Rolle.  \n\nLegen Sie nun den rechten Zeigefinger auf J (geordnete Zahlenfolgen & übereinstimmende Buchstabenfolgen) und den rechten Mittelfinger auf K (ungeordnete Zahlenfolgen & keine übereinstimmenden Buchstabenfolgen).  \n\nDer Übungsdurchlauf ist nun beendet. \nDrücken sie J, um mit der tatsächlichen Testung zu beginnen.';

export const INSTRUCTION_DUAL_PHON_J_PRACTICE = ' In den folgenden Folien wird Ihnen eine Buchstabenfolge präsentiert, die Sie sich einprägen sollen. \nDanach wird Ihnen ein Fixationspunkt, auf den Sie sich konzentrieren sollen, präsentiert. \nDanach ist kurz eine Zahlenfolge zu sehen. \nSobald sie die Zahlenfolge sehen sollen Sie so schnell wie möglich entscheiden, ob die gesehen Zahlenfolge geordnet (also aufsteigend oder absteigend) oder vollkommen ungeordnet war. \nWenn die gesehene Zahlenfolge geordnet (aufsteigend oder absteigend) war drücken Sie J. \nWenn die Zahlenfolge ungeordnet war, drücken Sie K. \nNach der Antwort sehen Sie erneut einen Fixationspunkt. \nAnschließend sehen Sie erneut eine Buchstabenfolge. \nSie sollen nun entscheiden, ob diese Buchstabenfolge, mit der zu Beginn Gezeigten übereinstimmt. \nSollte dies der Fall sein, drücken Sie J, sollten sich die zwei Buchstabenfolgen voneinander unterscheiden drücken Sie K. \nBitte verwenden Sie hierfür jeweils den Zeigefinger und den Mittelfinger der rechten Hand. \nDieser Ablauf wiederholt sich mehrmals.  \nAchtung! Hierbei spielt Groß- und Kleinschreibung keine Rolle.  \n\nLegen Sie nun den rechten Zeigefinger auf J (geordnete Zahlenfolgen & übereinstimmende Buchstabenfolgen) und den rechten Mittelfinger auf K (ungeordnete Zahlenfolgen & keine übereinstimmenden Buchstabenfolgen).  \n\nWenn Sie die Instruktion verstanden haben drücken sie J, um mit Übungsdurchgängen zur Aufgabe zu starten.';


export const INSTRUCTION_DUAL_PHON_K= ' In den folgenden Folien wird Ihnen eine Buchstabenfolge präsentiert, die Sie sich einprägen sollen. \nDanach wird Ihnen ein Fixationspunkt, auf den Sie sich konzentrieren sollen, präsentiert. \nDanach ist kurz eine Zahlenfolge zu sehen. \nSobald sie die Zahlenfolge sehen sollen Sie so schnell wie möglich entscheiden, ob die gesehen Zahlenfolge geordnet (also aufsteigend oder absteigend) oder vollkommen ungeordnet war. \nWenn die gesehene Zahlenfolge geordnet (aufsteigend oder absteigend) war drücken Sie K. \nWenn die Zahlenfolge ungeordnet war, drücken Sie J. \nNach der Antwort sehen Sie erneut einen Fixationspunkt. \nAnschließend sehen Sie erneut eine Buchstabenfolge. \nSie sollen nun entscheiden, ob diese Buchstabenfolge, mit der zu Beginn Gezeigten übereinstimmt. \nSollte dies der Fall sein, drücken Sie K, sollten sich die zwei Buchstabenfolgen voneinander unterscheiden drücken Sie J. \nBitte verwenden Sie hierfür jeweils den Zeigefinger und den Mittelfinger der rechten Hand. \nDieser Ablauf wiederholt sich mehrmals.  \nAchtung! Hierbei spielt Groß- und Kleinschreibung keine Rolle.  \n\nLegen Sie nun den rechten Zeigefinger auf J (ungeordnete Zahlenfolgen & keine übereinstimmenden Buchstabenfolgen) und den rechten Mittelfinger auf K (geordnete Zahlenfolgen & übereinstimmende Buchstabenfolgen).  \n\nDer Übungsdurchlauf ist nun beendet. \nDrücken sie K, um mit der tatsächlichen Testung zu beginnen.';

export const INSTRUCTION_DUAL_PHON_K_PRACTICE = ' In den folgenden Folien wird Ihnen eine Buchstabenfolge präsentiert, die Sie sich einprägen sollen. \nDanach wird Ihnen ein Fixationspunkt, auf den Sie sich konzentrieren sollen, präsentiert. \nDanach ist kurz eine Zahlenfolge zu sehen. \nSobald sie die Zahlenfolge sehen sollen Sie so schnell wie möglich entscheiden, ob die gesehen Zahlenfolge geordnet (also aufsteigend oder absteigend) oder vollkommen ungeordnet war. \nWenn die gesehene Zahlenfolge geordnet (aufsteigend oder absteigend) war drücken Sie K. \nWenn die Zahlenfolge ungeordnet war, drücken Sie J. \nNach der Antwort sehen Sie erneut einen Fixationspunkt. \nAnschließend sehen Sie erneut eine Buchstabenfolge. \nSie sollen nun entscheiden, ob diese Buchstabenfolge, mit der zu Beginn Gezeigten übereinstimmt. \nSollte dies der Fall sein, drücken Sie K, sollten sich die zwei Buchstabenfolgen voneinander unterscheiden drücken Sie J. \nBitte verwenden Sie hierfür jeweils den Zeigefinger und den Mittelfinger der rechten Hand. \nDieser Ablauf wiederholt sich mehrmals.  \nAchtung! Hierbei spielt Groß- und Kleinschreibung keine Rolle.  \n\nLegen Sie nun den rechten Zeigefinger auf J (ungeordnete Zahlenfolgen & keine übereinstimmenden Buchstabenfolgen) und den rechten Mittelfinger auf K (geordnete Zahlenfolgen & übereinstimmende Buchstabenfolgen).  \n\nWenn Sie die Instruktion verstanden haben drücken sie K, um mit Übungsdurchgängen zur Aufgabe zu starten.';





export const INSTRUCTION_DUAL_VIS_J= 'In den folgenden Folien wird Ihnen ein Muster präsentiert, die Sie sich einprägen sollen. \nDanach wird Ihnen ein Fixationspunkt, auf den Sie sich konzentrieren sollen, präsentiert. \nDanach ist kurz eine Zahlenfolge zu sehen. \nSobald sie die Zahlenfolge sehen sollen Sie entscheiden, ob die gesehen Zahlenfolge geordnet (also aufsteigend oder absteigend) oder vollkommen ungeordnet war. \nWenn die gesehene Zahlenfolge geordnet (aufsteigend oder absteigend) war drücken Sie J. \nWenn die Zahlenfolge ungeordnet war, drücken Sie K. \nNach der Antwort sehen Sie erneut einen Fixationspunkt. \nAnschließend sehen Sie erneut ein Muster. \nSie sollen nun entscheiden, ob dieses Muster, mit dem zu Beginn Gezeigten übereinstimmt. \nSollte dies der Fall sein, drücken Sie J, sollten sich die zwei Muster voneinander unterscheiden drücken Sie K. \nDieser Ablauf wiederholt sich mehrmals.  \n\nLegen Sie nun den rechten Zeigefinger auf J (geordnete Zahlenfolgen & übereinstimmende Muster) und den rechten Mittelfinger auf K (ungeordnete Zahlenfolgen & keine übereinstimmenden Muster).  \n\nDer Übungsdurchlauf ist nun beendet. \nDrücken sie J, um mit der tatsächlichen Testung zu beginnen.';

export const INSTRUCTION_DUAL_VIS_J_PRACTICE ='In den folgenden Folien wird Ihnen ein Muster präsentiert, die Sie sich einprägen sollen. \nDanach wird Ihnen ein Fixationspunkt, auf den Sie sich konzentrieren sollen, präsentiert. \nDanach ist kurz eine Zahlenfolge zu sehen. \nSobald sie die Zahlenfolge sehen sollen Sie entscheiden, ob die gesehen Zahlenfolge geordnet (also aufsteigend oder absteigend) oder vollkommen ungeordnet war. \nWenn die gesehene Zahlenfolge geordnet (aufsteigend oder absteigend) war drücken Sie J. \nWenn die Zahlenfolge ungeordnet war, drücken Sie K. \nNach der Antwort sehen Sie erneut einen Fixationspunkt. \nAnschließend sehen Sie erneut ein Muster. \nSie sollen nun entscheiden, ob dieses Muster, mit dem zu Beginn Gezeigten übereinstimmt. \nSollte dies der Fall sein, drücken Sie J, sollten sich die zwei Muster voneinander unterscheiden drücken Sie K. \nDieser Ablauf wiederholt sich mehrmals.  \n\nLegen Sie nun den rechten Zeigefinger auf J (geordnete Zahlenfolgen & übereinstimmende Muster) und den rechten Mittelfinger auf K (ungeordnete Zahlenfolgen & keine übereinstimmenden Muster).  \n\nWenn Sie die Instruktion verstanden haben drücken sie J, um mit Übungsdurchgängen zur Aufgabe zu starten.';


export const INSTRUCTION_DUAL_VIS_K= 'In den folgenden Folien wird Ihnen ein Muster präsentiert, die Sie sich einprägen sollen. \nDanach wird Ihnen ein Fixationspunkt, auf den Sie sich konzentrieren sollen, präsentiert. \nDanach ist kurz eine Zahlenfolge zu sehen. \nSobald sie die Zahlenfolge sehen sollen Sie entscheiden, ob die gesehen Zahlenfolge geordnet (also aufsteigend oder absteigend) oder vollkommen ungeordnet war. \nWenn die gesehene Zahlenfolge geordnet (aufsteigend oder absteigend) war drücken Sie K. \nWenn die Zahlenfolge ungeordnet war, drücken Sie J. \nNach der Antwort sehen Sie erneut einen Fixationspunkt. \nAnschließend sehen Sie erneut ein Muster. \nSie sollen nun entscheiden, ob dieses Muster, mit dem zu Beginn Gezeigten übereinstimmt. \nSollte dies der Fall sein, drücken Sie K, sollten sich die zwei Muster voneinander unterscheiden drücken Sie J. \nDieser Ablauf wiederholt sich mehrmals.  \n\nLegen Sie nun den rechten Zeigefinger auf J (ungeordnete Zahlenfolgen & keine übereinstimmenden Muster) und den rechten Mittelfinger auf K (geordnete Zahlenfolgen & übereinstimmende Muster).  \n\nDer Übungsdurchlauf ist nun beendet. \nDrücken sie K, um mit der tatsächlichen Testung zu beginnen.';

export const INSTRUCTION_DUAL_VIS_K_PRACTICE = 'In den folgenden Folien wird Ihnen zunächst ein Fixationspunkt, auf den Sie sich konzentrieren sollen, präsentiert. \nDanach ist kurz eine Zahlenfolge zu sehen. \nSobald sie die Zahlenfolge sehen sollen Sie entscheiden, ob die gesehen Zahlenfolge geordnet (also aufsteigend oder absteigend) oder vollkommen ungeordnet war. \nWenn die gesehene Zahlenfolge geordnet (aufsteigend oder absteigend) war drücken Sie J. \nWenn die Zahlenfolge ungeordnet war, drücken Sie K. \nBitte verwenden Sie hierfür den Zeigefinger und den Mittelfinger der rechten Hand. \nNach der Antwort sehen Sie erneut einen Fixationspunkt. \nDieser Ablauf wiederholt sich mehrmals.  \n\nLegen Sie nun den rechten Zeigefinger auf J (geordnete Zahlenfolge) und den rechten Mittelfinger auf K (ungeordnete Zahlenfolge).  \n\nWenn Sie die Instruktion verstanden haben drücken sie K, um mit Übungsdurchgängen zur Aufgabe zu starten.  \n';


export const INSTRUCTION_RIG_J= 'In den folgenden Folien wird Ihnen zunächst ein Fixationspunkt, auf den Sie sich konzentrieren sollen, präsentiert. \nDanach ist kurz eine Zahlenfolge zu sehen. \nSobald sie die Zahlenfolge sehen, sollen Sie entscheiden, ob diese geordnet (also aufsteigend oder absteigend) oder ungeordnet war. \nWenn die gesehene Zahlenfolge geordnet (aufsteigend oder absteigend) war drücken Sie J. \nWenn die Zahlenfolge ungeordnet war, drücken Sie K. \nHierfür verwenden Sie den Zeigefinger und den Mittelfinger der rechten Hand. \nNach der Antwort sehen Sie erneut einen Fixationspunkt. \nDieser Ablauf wiederholt sich mehrmals.  \nWährend Sie die oben beschriebene Aufgabe bearbeiten, müssen Sie durchgehend ein zufälliges Intervall (kein gleichbleibender Rhythmus!!) auf der Tastatur drücken. \nHierbei drücken Sie die S-Taste in vollkommen zufälligen Abständen mit dem Zeigefinger der linken Hand.  \n\nLegen Sie nun den rechten Zeigefinger auf J (geordnete Zahlenfolge) und den rechten Mittelfinger auf K (ungeordnete Zahlenfolge), sowie den linken Zeigefinger auf S (=unregelmäßiger Rhythmus während der gesamten Aufgabe).  \n\nDer Übungsdurchlauf ist nun beendet. \nDrücken sie J, um mit der tatsächlichen Testung zu beginnen.  \n';


export const INSTRUCTION_RIG_J_PRACTICE = 'In den folgenden Folien wird Ihnen zunächst ein Fixationspunkt, auf den Sie sich konzentrieren sollen, präsentiert. \nDanach ist kurz eine Zahlenfolge zu sehen. \nSobald sie die Zahlenfolge sehen, sollen Sie entscheiden, ob diese geordnet (also aufsteigend oder absteigend) oder ungeordnet war. \nWenn die gesehene Zahlenfolge geordnet (aufsteigend oder absteigend) war drücken Sie J. \nWenn die Zahlenfolge ungeordnet war, drücken Sie K. \nHierfür verwenden Sie den Zeigefinger und den Mittelfinger der rechten Hand. \nNach der Antwort sehen Sie erneut einen Fixationspunkt. \nDieser Ablauf wiederholt sich mehrmals.  \nWährend Sie die oben beschriebene Aufgabe bearbeiten, müssen Sie durchgehend ein zufälliges Intervall (kein gleichbleibender Rhythmus!!) auf der Tastatur drücken. \nHierbei drücken Sie die S-Taste in vollkommen zufälligen Abständen mit dem Zeigefinger der linken Hand.  \n\nLegen Sie nun den rechten Zeigefinger auf J (geordnete Zahlenfolge) und den rechten Mittelfinger auf K (ungeordnete Zahlenfolge), sowie den linken Zeigefinger auf S (=unregelmäßiger Rhythmus während der gesamten Aufgabe).  \n\nWenn Sie die Instruktion verstanden haben drücken sie J, um mit Übungsdurchgängen zur Aufgabe zu starten.  ';


export const INSTRUCTION_RIG_K= 'In den folgenden Folien wird Ihnen zunächst ein Fixationspunkt, auf den Sie sich konzentrieren sollen, präsentiert. \nDanach ist kurz eine Zahlenfolge zu sehen. \nSobald sie die Zahlenfolge sehen, sollen Sie entscheiden, ob diese geordnet (also aufsteigend oder absteigend) oder ungeordnet war. \nWenn die gesehene Zahlenfolge geordnet (aufsteigend oder absteigend) war drücken Sie K. \nWenn die Zahlenfolge ungeordnet war, drücken Sie J. \nHierfür verwenden Sie den Zeigefinger und den Mittelfinger der rechten Hand. \nNach der Antwort sehen Sie erneut einen Fixationspunkt. \nDieser Ablauf wiederholt sich mehrmals.  \nWährend Sie die oben beschriebene Aufgabe bearbeiten, müssen Sie durchgehend ein zufälliges Intervall (kein gleichbleibender Rhythmus!!) auf der Tastatur drücken. \nHierbei drücken Sie die S-Taste in vollkommen zufälligen Abständen mit dem Zeigefinger der linken Hand.  \n\nLegen Sie nun den rechten Zeigefinger auf K (geordnete Zahlenfolge) und den rechten Mittelfinger auf J (ungeordnete Zahlenfolge), sowie den linken Zeigefinger auf S (=unregelmäßiger Rhythmus während der gesamten Aufgabe).  \n\nDer Übungsdurchlauf ist nun beendet. \nDrücken sie K, um mit der tatsächlichen Testung zu beginnen.  \n';

export const INSTRUCTION_RIG_K_PRACTICE = 'In den folgenden Folien wird Ihnen zunächst ein Fixationspunkt, auf den Sie sich konzentrieren sollen, präsentiert. \nDanach ist kurz eine Zahlenfolge zu sehen. \nSobald sie die Zahlenfolge sehen, sollen Sie entscheiden, ob diese geordnet (also aufsteigend oder absteigend) oder ungeordnet war. \nWenn die gesehene Zahlenfolge geordnet (aufsteigend oder absteigend) war drücken Sie K. \nWenn die Zahlenfolge ungeordnet war, drücken Sie J. \nHierfür verwenden Sie den Zeigefinger und den Mittelfinger der rechten Hand. \nNach der Antwort sehen Sie erneut einen Fixationspunkt. \nDieser Ablauf wiederholt sich mehrmals.  \nWährend Sie die oben beschriebene Aufgabe bearbeiten, müssen Sie durchgehend ein zufälliges Intervall (kein gleichbleibender Rhythmus!!) auf der Tastatur drücken. \nHierbei drücken Sie die S-Taste in vollkommen zufälligen Abständen mit dem Zeigefinger der linken Hand.  \n\nLegen Sie nun den rechten Zeigefinger auf K (geordnete Zahlenfolge) und den rechten Mittelfinger auf J (ungeordnete Zahlenfolge), sowie den linken Zeigefinger auf S (=unregelmäßiger Rhythmus während der gesamten Aufgabe).  \n\nWenn Sie die Instruktion verstanden haben drücken sie K, um mit Übungsdurchgängen zur Aufgabe zu starten.  \n';

